### ISSUE TITLE
Doesn't seem to work for me on 4.2.0.rc3

### ISSUE THREAD

**Issue by jblauer** [tubbo/activejob-scheduler#1]
On rails 4.2.0.rc3

I follow these instructions

gem 'activejob-scheduler'
$ bundle
$ rails generate activejob:schedule

I get:

Could not find generator 'activejob:schedule'. Maybe you meant 'active_record:model' or 'erb:scaffold' or 'scss:scaffold'
Run `rails generate --help` for more options.

**Comment by zekefast** [comment]
@kyledecot, same for me.

There is a pull request for this issue. Do you have any info when you could merge it?
