### ISSUE TITLE
Can you suggest or add to documentation at which timezone job scheduler run?

### ISSUE THREAD

**Issue by zekefast** [tubbo/activejob-scheduler#4]
I think that this is a system time and timezone for system time will be in `/etc/timezone`, but it would be better to clarify. Could you?

Thank you in advance!

**Comment by tubbo** [comment]
it will run in the time zone specified by rails if you use the activesupport time helpers like `every: 3.days`. if you're using `:cron`, you'll need to add the time zone identifier to the end of the string like `"0 6 * * * #{Time.zone.tzinfo.identifier}"`.
